import type { BlockHeights, StatusSummary } from "@/lib/api";

export type CardKind = "bp" | "rpc" | "explorer" | "pavillion";

export type CardData = {
  id: string;
  nodeKey?: string;
  kind: CardKind;
  title: string;
  height: number | null;
  rpcFirstResponseMs?: number | null;
  rpcAverageResponseMs?: number | null;
  rpcVersion?: string | null;
  bpBuildVersion?: string | null;
  rpcCommit?: string | null;
  rpcBuildTimeUtc?: string | null;
  rpcDocsUrl?: string | null;
  explorerUrl?: string | null;
  explorerApiUrl?: string | null;
  explorerLastBlockHeight?: number | null;
  explorerLastBlockAgeSec?: number | null;
  explorerResponseMs?: number | null;
  pavNetwork?: string | null;
  pavOverallOk?: boolean | null;
  pavStatusAgeSec?: number | null;
  pavSecureNodes?: number | null;
  pavOutagesCount?: number | null;
  pavRpcPeerCount?: number | null;
  pavRpcPrimary?: string | null;
  pavApiUrl?: string | null;
  pavApiProbeOk?: boolean | null;
  pavApiError?: string | null;
  pavApiUptimeSec?: number | null;
  pavApiBuildTime?: string | null;
  pavApiBuildCommit?: string | null;
  pavApiBuildVersion?: string | null;
  pavClientUrl?: string | null;
  pavClientProbeOk?: boolean | null;
  pavClientError?: string | null;
  pavClientApiUrl?: string | null;
  pavClientBuildTime?: string | null;
  pavClientBuildCommit?: string | null;
  pavClientBuildBranch?: string | null;
  pavClientAppVersion?: string | null;
  pavClientSdkVersion?: string | null;
  pavShopUrl?: string | null;
  pavShopProbeOk?: boolean | null;
  pavShopError?: string | null;
  pavShopUptimeSec?: number | null;
  pavShopBuildVersion?: string | null;
  pavShopBuildCommit?: string | null;
  pavStatusProbeOk?: boolean | null;
  pavStatusOk?: boolean | null;
  pavStatusError?: string | null;
  pavRpcProbeOk?: boolean | null;
  pavRpcError?: string | null;
  heights?: BlockHeights | null;
  status?: StatusSummary | null;
  leader?: string | null;
  lastAppliedAgeSec?: number | null;
  avgProductionDelayMs?: number | null;
  avgVerificationDelayMs?: number | null;
  avgTransactions?: number | null;
  sparkline?: number[] | null;
  role?: string | null;
  error?: string | null;
};
